from typing import Callable


def bogo_sort(arr: list) -> list: ...

def is_sorted(arr: list) -> bool: ...

def bubble_sort(arr: list) -> list: ...

def merge(left: list, right: list) -> list: ...

def merge_sort(arr: list) -> Callable: ...
