# coding: utf-8

"""
    LinksGPT URL Shortener SDK

    LinksGPT URL Shortener SDK  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: service@linksgpt.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "linksgpt_url_shortener"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name=NAME,
    version=VERSION,
    description="LinksGPT URL Shortener Python SDK. It supports AI-driven URL shortening and expansion, custom domains, team roles, customizable QR codes, tracking and in-depth analytics, deep linking and enhanced link security.",
    author='LinksGPT',
    author_email="service@linksgpt.com",
    license='MIT License',
    url="https://github.com/LinksGPT/url-shortener-sdk-python",
    keywords=["LinksGPT", "URL Shortener", "URL Expander", "Short Link", "SEO"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description=long_description,
    long_description_content_type="text/markdown"
)
