
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_currency = {
    '$': [
        'aud',
        'bbd',
        'bmd',
        'bnd',
        'bsd',
        'bzd',
        'cad',
        'fjd',
        'gyd',
        'hkd',
        'jmd',
        'kyd',
        'lrd',
        'nad',
        'nzd',
        'sbd',
        'sgd',
        'srd',
        'twd',
        'usd',
        'xcd'
    ],
    '.د.م': ['mad'],
    'ft': ['huf'],
    'ksh': ['kes'],
    'kč': ['czk'],
    'l': ['ron'],
    'zł': ['pln'],
    '£': ['egp', 'fkp', 'gbp'],
    '¥': ['jpy'],
    'ƒ': ['awg'],
    'ξ': ['eth'],
    'лв': ['bgn'],
    '֏': ['amd'],
    'د.إ': ['aed'],
    'د.ك': ['kwd'],
    'ل.د': ['lyd'],
    'ل.ل': ['lbp'],
    '৳': ['bdt'],
    '฿': ['thb'],
    '₡': ['crc'],
    '₣': ['cdf', 'cfp', 'djf', 'gnf', 'xaf'],
    '₦': ['ngn'],
    '₩': ['krw'],
    '₪': ['ils'],
    '₫': ['vnd'],
    '€': ['eur'],
    '₭': ['lak'],
    '₱': ['mxn', 'php'],
    '₲': ['pyg'],
    '₴': ['uah'],
    '₵': ['ghs'],
    '₹': ['inr'],
    '₺': ['try'],
    '₽': ['rub'],
    '₾': ['gel'],
    '₿': ['btc'],
    '〒': ['kzt'],
    '元': ['cny']}
