from __future__ import annotations
import rdkix.Chem.Draw.canvasbase
from rdkix.Chem.Draw.canvasbase import CanvasBase
from rdkix.sping import pid
import re as re
__all__ = ['Canvas', 'CanvasBase', 'convertColor', 'faceMap', 'pid', 're']
class Canvas(rdkix.Chem.Draw.canvasbase.CanvasBase):
    def __init__(self, size, name, imageType = 'png'):
        ...
    def addCanvasDashedWedge(self, p1, p2, p3, dash = (2, 2), color = (0, 0, 0), color2 = None, **kwargs):
        ...
    def addCanvasLine(self, p1, p2, color = (0, 0, 0), color2 = None, **kwargs):
        ...
    def addCanvasPolygon(self, ps, color = (0, 0, 0), fill = True, stroke = False, **kwargs):
        ...
    def addCanvasText(self, text, pos, font, color = (0, 0, 0), **kwargs):
        ...
    def flush(self):
        ...
    def save(self):
        ...
def convertColor(color):
    ...
faceMap: dict = {'sans': 'helvetica', 'serif': 'times'}
