# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications  # noqa: E501

    The version of the OpenAPI document: 0.7.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from osparc_client.configuration import Configuration


class BodyCompleteMultipartUploadV0FilesFileIdCompletePost(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'client_file': 'ClientFile',
        'uploaded_parts': 'FileUploadCompletionBody'
    }

    attribute_map = {
        'client_file': 'client_file',
        'uploaded_parts': 'uploaded_parts'
    }

    def __init__(self, client_file=None, uploaded_parts=None, local_vars_configuration=None):  # noqa: E501
        """BodyCompleteMultipartUploadV0FilesFileIdCompletePost - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._client_file = None
        self._uploaded_parts = None
        self.discriminator = None

        self.client_file = client_file
        self.uploaded_parts = uploaded_parts

    @property
    def client_file(self):
        """Gets the client_file of this BodyCompleteMultipartUploadV0FilesFileIdCompletePost.  # noqa: E501


        :return: The client_file of this BodyCompleteMultipartUploadV0FilesFileIdCompletePost.  # noqa: E501
        :rtype: ClientFile
        """
        return self._client_file

    @client_file.setter
    def client_file(self, client_file):
        """Sets the client_file of this BodyCompleteMultipartUploadV0FilesFileIdCompletePost.


        :param client_file: The client_file of this BodyCompleteMultipartUploadV0FilesFileIdCompletePost.  # noqa: E501
        :type: ClientFile
        """
        if self.local_vars_configuration.client_side_validation and client_file is None:  # noqa: E501
            raise ValueError("Invalid value for `client_file`, must not be `None`")  # noqa: E501

        self._client_file = client_file

    @property
    def uploaded_parts(self):
        """Gets the uploaded_parts of this BodyCompleteMultipartUploadV0FilesFileIdCompletePost.  # noqa: E501


        :return: The uploaded_parts of this BodyCompleteMultipartUploadV0FilesFileIdCompletePost.  # noqa: E501
        :rtype: FileUploadCompletionBody
        """
        return self._uploaded_parts

    @uploaded_parts.setter
    def uploaded_parts(self, uploaded_parts):
        """Sets the uploaded_parts of this BodyCompleteMultipartUploadV0FilesFileIdCompletePost.


        :param uploaded_parts: The uploaded_parts of this BodyCompleteMultipartUploadV0FilesFileIdCompletePost.  # noqa: E501
        :type: FileUploadCompletionBody
        """
        if self.local_vars_configuration.client_side_validation and uploaded_parts is None:  # noqa: E501
            raise ValueError("Invalid value for `uploaded_parts`, must not be `None`")  # noqa: E501

        self._uploaded_parts = uploaded_parts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BodyCompleteMultipartUploadV0FilesFileIdCompletePost):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BodyCompleteMultipartUploadV0FilesFileIdCompletePost):
            return True

        return self.to_dict() != other.to_dict()
