# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications  # noqa: E501

    The version of the OpenAPI document: 0.7.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from osparc_client.configuration import Configuration


class FileUploadData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'chunk_size': 'int',
        'urls': 'list[str]',
        'links': 'UploadLinks'
    }

    attribute_map = {
        'chunk_size': 'chunk_size',
        'urls': 'urls',
        'links': 'links'
    }

    def __init__(self, chunk_size=None, urls=None, links=None, local_vars_configuration=None):  # noqa: E501
        """FileUploadData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._chunk_size = None
        self._urls = None
        self._links = None
        self.discriminator = None

        self.chunk_size = chunk_size
        self.urls = urls
        self.links = links

    @property
    def chunk_size(self):
        """Gets the chunk_size of this FileUploadData.  # noqa: E501


        :return: The chunk_size of this FileUploadData.  # noqa: E501
        :rtype: int
        """
        return self._chunk_size

    @chunk_size.setter
    def chunk_size(self, chunk_size):
        """Sets the chunk_size of this FileUploadData.


        :param chunk_size: The chunk_size of this FileUploadData.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and chunk_size is None:  # noqa: E501
            raise ValueError("Invalid value for `chunk_size`, must not be `None`")  # noqa: E501

        self._chunk_size = chunk_size

    @property
    def urls(self):
        """Gets the urls of this FileUploadData.  # noqa: E501


        :return: The urls of this FileUploadData.  # noqa: E501
        :rtype: list[str]
        """
        return self._urls

    @urls.setter
    def urls(self, urls):
        """Sets the urls of this FileUploadData.


        :param urls: The urls of this FileUploadData.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and urls is None:  # noqa: E501
            raise ValueError("Invalid value for `urls`, must not be `None`")  # noqa: E501

        self._urls = urls

    @property
    def links(self):
        """Gets the links of this FileUploadData.  # noqa: E501


        :return: The links of this FileUploadData.  # noqa: E501
        :rtype: UploadLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this FileUploadData.


        :param links: The links of this FileUploadData.  # noqa: E501
        :type: UploadLinks
        """
        if self.local_vars_configuration.client_side_validation and links is None:  # noqa: E501
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileUploadData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FileUploadData):
            return True

        return self.to_dict() != other.to_dict()
