
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-20T20:10:14+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "ffa00f95bfdc0fb134e79d7f0ee0e54ef642e2cf",
 "version": "0.2.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
