install.packages(c("devtools", "knitr", "DirichletReg"))
library(devtools)
devtools::install_github("sqyu/genscore")
devtools::install_github("syma-research/CompDA")
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
library(BiocManager)
BiocManager::install(c("ANCOMBC", "phyloseq"))
