"""
Generated by Sideko (sideko.dev)
"""

import typing_extensions
import pydantic


class PostV1AiQrCodeGeneratorBodyStyle(typing_extensions.TypedDict):
    """ """

    art_style: typing_extensions.Required[str]


class _SerializerPostV1AiQrCodeGeneratorBodyStyle(pydantic.BaseModel):
    """
    Serializer for PostV1AiQrCodeGeneratorBodyStyle handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    art_style: str = pydantic.Field(alias="art_style")
