from enum import Enum

DEFAULT_OUTPUT_ARE = False
DEFAULT_OUTPUT_ARE_JSON = True
DEFAULT_OUTPUT_PNG = True
DEFAULT_OUTPUT_TILE_JSON = False
DEFAULT_OUTPUT_TREE = False

DEFAULT_MAP_BEND_PCT = 50
DEFAULT_MAP_DEADENDS_PCT = 50
DEFAULT_MAP_HEIGHT = 17
DEFAULT_MAP_MAX_ROOMS = None
DEFAULT_MAP_MIN_ROOMS = 1
DEFAULT_MAP_RESHAPE_PCT = 70
DEFAULT_MAP_ROOM_RATIO = 100
DEFAULT_MAP_WIDTH = DEFAULT_MAP_HEIGHT

DEFAULT_PNG_AXES_IDS = False
DEFAULT_PNG_AXES_BASE = 1
DEFAULT_PNG_DEBUG = False
DEFAULT_PNG_GRID_SIZE = 20
DEFAULT_PNG_ROOM_IDS = True
DEFAULT_PNG_TILESET_IDX = False


class Directions(Enum):
    NORTH = 1
    SOUTH = 2
    EAST = 3
    WEST = 4


DIRECTIONS_X = {Directions.NORTH: 0, Directions.SOUTH: 0, Directions.EAST: 1, Directions.WEST: -1}
DIRECTIONS_Y = {Directions.NORTH: -1, Directions.SOUTH: 1, Directions.EAST: 0, Directions.WEST: 0}
DIRECTIONS = (Directions.NORTH, Directions.EAST, Directions.SOUTH, Directions.WEST)
