# coding: utf-8

"""
    Maneuver Planning API

    Maneuver Planning API

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_maneuver_planning_python_client.models.earth_centered_frame_id import EarthCenteredFrameId

class TestEarthCenteredFrameId(unittest.TestCase):
    """EarthCenteredFrameId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEarthCenteredFrameId(self):
        """Test EarthCenteredFrameId"""
        # inst = EarthCenteredFrameId()

if __name__ == '__main__':
    unittest.main()
