# coding: utf-8

"""
    Maneuver Planning API

    Maneuver Planning API

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_maneuver_planning_python_client.models.celestial_body_name import CelestialBodyName

class TestCelestialBodyName(unittest.TestCase):
    """CelestialBodyName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCelestialBodyName(self):
        """Test CelestialBodyName"""
        # inst = CelestialBodyName()

if __name__ == '__main__':
    unittest.main()
