# Generated by Django 5.1.2 on 2024-11-09 18:38
import kitchenai.core.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_kitchenaimanagement_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(upload_to=kitchenai.core.models.file_object_directory_path),
                ),
                ("name", models.CharField(max_length=255)),
                ("ingest_label", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
