from argparse import ArgumentParser, Namespace
from proyo.proyo import Proyo

# Only import this from within proyo scripts
# These locals will be populated by the Proyo instance
proyo: Proyo = ...
args: Namespace = ...
parser: ArgumentParser = ...
