from _typeshed import Incomplete
from datetime import datetime
from dojo.common.constants import Chain as Chain
from dojo.config import cfg as cfg
from web3.types import Timestamp

memory: Incomplete

def block_to_timestamp(rpc_url: str, block_number: int) -> Timestamp: ...
def block_to_datetime(rpc_url: str, block_number: int) -> datetime: ...
def closest_block_to(datetime_: datetime, chain: Chain) -> int: ...
def closest_block_lt(datetime_: datetime, chain: Chain) -> int: ...
