# coding: utf-8

"""
    Maneuver Planning API

    Maneuver Planning API

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FixedStepIntegratorType(str, Enum):
    """
    FixedStepIntegratorType
    """

    """
    allowed enum values
    """
    RUNGE_KUTTA_4 = 'RUNGE_KUTTA_4'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FixedStepIntegratorType from a JSON string"""
        return cls(json.loads(json_str))


