#------------------------------------------------------------------------------
# <auto-generated>
#     This file was auto generated.
#
#     Changes to this file may cause incorrect behavior and will be lost if
#     the code is regenerated.
# </auto-generated>
#------------------------------------------------------------------------------
import typing
from abc import abstractmethod, ABCMeta


# noinspection PyPep8Naming
class IDesignCode(metaclass=ABCMeta):
    """A design code
    """
    pass


# noinspection PyPep8Naming
class AASHTO(metaclass=ABCMeta):


    # noinspection PyPep8Naming
    class Edition_2017(metaclass=ABCMeta):

        Metric: IDesignCode = ...

        US: IDesignCode = ...


# noinspection PyPep8Naming
class ACI318(metaclass=ABCMeta):


    # noinspection PyPep8Naming
    class Edition_2002(metaclass=ABCMeta):

        Metric: IDesignCode = ...

        US: IDesignCode = ...


    # noinspection PyPep8Naming
    class Edition_2005(metaclass=ABCMeta):

        Metric: IDesignCode = ...

        US: IDesignCode = ...


    # noinspection PyPep8Naming
    class Edition_2008(metaclass=ABCMeta):

        Metric: IDesignCode = ...

        US: IDesignCode = ...


    # noinspection PyPep8Naming
    class Edition_2011(metaclass=ABCMeta):

        Metric: IDesignCode = ...

        US: IDesignCode = ...


    # noinspection PyPep8Naming
    class Edition_2014(metaclass=ABCMeta):

        Metric: IDesignCode = ...

        US: IDesignCode = ...


# noinspection PyPep8Naming
class AS3600(metaclass=ABCMeta):

    Edition_2001: IDesignCode = ...
    """The 2001 edition of AS3600
    """

    Edition_2009: IDesignCode = ...
    """The 2009 edition of AS3600
    """

    Edition_2018: IDesignCode = ...
    """The 2018 edition of AS3600
    """


# noinspection PyPep8Naming
class AS5100(metaclass=ABCMeta):

    Edition_2017: IDesignCode = ...
    """The 2017 edition of AS5100
    """


# noinspection PyPep8Naming
class EN1992(metaclass=ABCMeta):


    # noinspection PyPep8Naming
    class Part1_1(metaclass=ABCMeta):


        # noinspection PyPep8Naming
        class Edition_2004(metaclass=ABCMeta):


            # noinspection PyPep8Naming
            class NationalAnnex(metaclass=ABCMeta):

                NoNationalAnnex: IDesignCode = ...


                # noinspection PyPep8Naming
                class DE(metaclass=ABCMeta):

                    Edition_2013: IDesignCode = ...


                # noinspection PyPep8Naming
                class DK(metaclass=ABCMeta):

                    Edition_2013: IDesignCode = ...


                # noinspection PyPep8Naming
                class ES(metaclass=ABCMeta):

                    Edition_2013: IDesignCode = ...


                # noinspection PyPep8Naming
                class FI(metaclass=ABCMeta):

                    Edition_2017: IDesignCode = ...


                # noinspection PyPep8Naming
                class FR(metaclass=ABCMeta):

                    Edition_2016: IDesignCode = ...


                # noinspection PyPep8Naming
                class GB(metaclass=ABCMeta):

                    Edition_2014: IDesignCode = ...


                    # noinspection PyPep8Naming
                    class PD6687(metaclass=ABCMeta):

                        Edition_2006: IDesignCode = ...

                        Edition_2010: IDesignCode = ...


                # noinspection PyPep8Naming
                class IE(metaclass=ABCMeta):

                    Edition_2010: IDesignCode = ...


                # noinspection PyPep8Naming
                class IT(metaclass=ABCMeta):

                    Edition_2007: IDesignCode = ...


                # noinspection PyPep8Naming
                class NL(metaclass=ABCMeta):

                    Edition_2020: IDesignCode = ...


                # noinspection PyPep8Naming
                class NO(metaclass=ABCMeta):

                    Edition_2010: IDesignCode = ...


                # noinspection PyPep8Naming
                class PL(metaclass=ABCMeta):

                    Edition_2008: IDesignCode = ...


                # noinspection PyPep8Naming
                class SG(metaclass=ABCMeta):

                    Edition_2008: IDesignCode = ...


                # noinspection PyPep8Naming
                class CY(metaclass=ABCMeta):

                    Edition_2019: IDesignCode = ...


    # noinspection PyPep8Naming
    class Part2(metaclass=ABCMeta):


        # noinspection PyPep8Naming
        class Edition_2005(metaclass=ABCMeta):


            # noinspection PyPep8Naming
            class NationalAnnex(metaclass=ABCMeta):

                NoNationalAnnex: IDesignCode = ...


                # noinspection PyPep8Naming
                class DE(metaclass=ABCMeta):

                    Edition_2013: IDesignCode = ...


                # noinspection PyPep8Naming
                class DK(metaclass=ABCMeta):

                    Edition_2015: IDesignCode = ...


                # noinspection PyPep8Naming
                class ES(metaclass=ABCMeta):

                    Edition_2013: IDesignCode = ...


                # noinspection PyPep8Naming
                class FR(metaclass=ABCMeta):

                    Edition_2007: IDesignCode = ...


                # noinspection PyPep8Naming
                class GB(metaclass=ABCMeta):

                    Edition_2007: IDesignCode = ...


                # noinspection PyPep8Naming
                class IE(metaclass=ABCMeta):

                    Edition_2005: IDesignCode = ...


                # noinspection PyPep8Naming
                class IT(metaclass=ABCMeta):

                    Edition_2006: IDesignCode = ...


                # noinspection PyPep8Naming
                class NL(metaclass=ABCMeta):

                    Edition_2016: IDesignCode = ...


                # noinspection PyPep8Naming
                class SG(metaclass=ABCMeta):

                    Edition_2012: IDesignCode = ...


# noinspection PyPep8Naming
class BS5400(metaclass=ABCMeta):

    Edition_1990: IDesignCode = ...
    """The 1990 edition of BS5400
    """

    Edition_2006: IDesignCode = ...
    """The 2006 edition of BS5400 including Interim Advice Note 70/06
    """


# noinspection PyPep8Naming
class BS8110(metaclass=ABCMeta):

    Edition_1985: IDesignCode = ...
    """The 1985 edition of BS8110
    """

    Edition_1997: IDesignCode = ...
    """The 1997 edition of BS8110
    """

    Edition_2005: IDesignCode = ...
    """The 2005 edition of BS8110
    """


# noinspection PyPep8Naming
class CSA(metaclass=ABCMeta):


    # noinspection PyPep8Naming
    class A23_3(metaclass=ABCMeta):

        Edition_2004: IDesignCode = ...

        Edition_2014: IDesignCode = ...


    # noinspection PyPep8Naming
    class S6(metaclass=ABCMeta):

        Edition_2014: IDesignCode = ...


# noinspection PyPep8Naming
class HK(metaclass=ABCMeta):


    # noinspection PyPep8Naming
    class CP(metaclass=ABCMeta):

        Edition_1987: IDesignCode = ...

        Edition_2004: IDesignCode = ...

        Edition_2007: IDesignCode = ...

        Edition_2013: IDesignCode = ...


    # noinspection PyPep8Naming
    class SDM(metaclass=ABCMeta):

        Edition_2002: IDesignCode = ...

        Edition_2013: IDesignCode = ...


# noinspection PyPep8Naming
class IRC112(metaclass=ABCMeta):

    Edition_2011: IDesignCode = ...
    """The 2011 edition of IRC112
    """


# noinspection PyPep8Naming
class IRS(metaclass=ABCMeta):

    Edition_1997: IDesignCode = ...
    """The 1997 edition of IRS Bridge
    """


# noinspection PyPep8Naming
class IS456(metaclass=ABCMeta):

    Edition_2000: IDesignCode = ...
    """The 2000 edition of IS456
    """
