key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIHQKR027PpIL3jmuBY5pi1vyf2rPKrwD82nunY3W3TMmoAoGCCqGSM49
AwEHoUQDQgAEfytUFoMyXqYe6oxI6aEnlC1Dus/7BwNUF+nIImcZfu4FsB5MABaY
eAcizNFQoYjdraGBnzf5jTrq6e1RpPXp1w==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIIB6jCCAY8CFCxDTDYHKrP92XJ2rvne0cPov0MwMAoGCCqGSM49BAMCMHcxCzAJ
BgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UE
CgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25hbCBVbml0MRQw
EgYDVQQDDAtDb21tb24gTmFtZTAeFw0yNDExMTgwNjMzMDBaFw0zNDExMTYwNjMz
MDBaMHcxCzAJBgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0
eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25h
bCBVbml0MRQwEgYDVQQDDAtDb21tb24gTmFtZTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABH8rVBaDMl6mHuqMSOmhJ5QtQ7rP+wcDVBfpyCJnGX7uBbAeTAAWmHgH
IszRUKGI3a2hgZ83+Y066untUaT16dcwCgYIKoZIzj0EAwIDSQAwRgIhAJVuVStG
fi//wdAZFxzyRDltvFzKRbaCevD+roKvQU1cAiEAldq+ezbZqZ+PTDnDfHhWVaat
L3s8iEZU0khAttFpXVo=
-----END CERTIFICATE-----
"""