#------------------------------------------------------------------------------
# <auto-generated>
#     This file was auto generated.
#
#     Changes to this file may cause incorrect behavior and will be lost if
#     the code is regenerated.
# </auto-generated>
#------------------------------------------------------------------------------
import typing
from abc import abstractmethod, ABCMeta
from System.Collections import IEnumerable
from System.Collections.Generic import ICollection, IEnumerable, IList
T = typing.TypeVar('T')


# noinspection PyPep8Naming
class IList(IList[T], ICollection[T], IEnumerable[T], IEnumerable, typing.Generic[T], metaclass=ABCMeta):
    """A customised version "System.Collections.Generic.IList{T}"

    See IList for more information

    The type of elements in the list.
    """

    @staticmethod
    def Create() -> IList[T]:
        """Creates an empty list
        """
        pass
