
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: envoy.distribution.distrotest:package

from setuptools import setup

setup(**{
    'author': 'Ryan Northey',
    'author_email': 'ryan@synca.io',
    'description': '"Lib for testing packages with distributions in Envoy proxy\'s CI"',
    'install_requires': (
        'aio.run.checker>=0.5.8',
        'envoy.base.utils>=0.5.7',
        'envoy.docker.utils>=0.0.2',
    ),
    'license': 'Apache Software License 2.0',
    'long_description': """
envoy.distribution.distrotest
=============================

Lib for testing packages with distributions in Envoy proxy's CI
""",
    'maintainer': 'Ryan Northey',
    'maintainer_email': 'ryan@synca.io',
    'name': 'envoy.distribution.distrotest',
    'namespace_packages': (
    ),
    'package_data': {
        'envoy.distribution.distrotest': (
            'distrotest.sh',
            'distrotest.yaml',
            'py.typed',
        ),
    },
    'packages': (
        'envoy.distribution.distrotest',
    ),
    'python_requires': '>=3.11.0',
    'url': 'https://github.com/envoyproxy/toolshed/tree/main/envoy.distribution.distrotest',
    'version': '0.0.11',
})
