# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ondewo.vtsi import calls_pb2 as ondewo_dot_vtsi_dot_calls__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},' +
        f' but the generated code in ondewo/vtsi/calls_pb2_grpc.py depends on' +
        f' grpcio>={GRPC_GENERATED_VERSION}.' +
        f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}' +
        f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CallsStub(object):
    """ONDEWO VTSI API
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartCaller = channel.unary_unary(
            '/ondewo.vtsi.Calls/StartCaller',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallerRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallerResponse.FromString,
            _registered_method=True)
        self.StartCallers = channel.unary_unary(
            '/ondewo.vtsi.Calls/StartCallers',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallersRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallersResponse.FromString,
            _registered_method=True)
        self.ListCallers = channel.unary_unary(
            '/ondewo.vtsi.Calls/ListCallers',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallersRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallersResponse.FromString,
            _registered_method=True)
        self.GetCaller = channel.unary_unary(
            '/ondewo.vtsi.Calls/GetCaller',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.GetCallerRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.Caller.FromString,
            _registered_method=True)
        self.DeleteCaller = channel.unary_unary(
            '/ondewo.vtsi.Calls/DeleteCaller',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallerRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallerResponse.FromString,
            _registered_method=True)
        self.DeleteCallers = channel.unary_unary(
            '/ondewo.vtsi.Calls/DeleteCallers',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallersRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallersResponse.FromString,
            _registered_method=True)
        self.StopCaller = channel.unary_unary(
            '/ondewo.vtsi.Calls/StopCaller',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallerRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallerResponse.FromString,
            _registered_method=True)
        self.StopCallers = channel.unary_unary(
            '/ondewo.vtsi.Calls/StopCallers',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallersRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallersResponse.FromString,
            _registered_method=True)
        self.StartListener = channel.unary_unary(
            '/ondewo.vtsi.Calls/StartListener',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenerRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenerResponse.FromString,
            _registered_method=True)
        self.StartListeners = channel.unary_unary(
            '/ondewo.vtsi.Calls/StartListeners',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenersRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenersResponse.FromString,
            _registered_method=True)
        self.StopListener = channel.unary_unary(
            '/ondewo.vtsi.Calls/StopListener',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenerRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenerResponse.FromString,
            _registered_method=True)
        self.StopListeners = channel.unary_unary(
            '/ondewo.vtsi.Calls/StopListeners',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenersRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenersResponse.FromString,
            _registered_method=True)
        self.ListListeners = channel.unary_unary(
            '/ondewo.vtsi.Calls/ListListeners',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListListenersRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListListenersResponse.FromString,
            _registered_method=True)
        self.GetListener = channel.unary_unary(
            '/ondewo.vtsi.Calls/GetListener',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.GetListenerRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.Listener.FromString,
            _registered_method=True)
        self.DeleteListener = channel.unary_unary(
            '/ondewo.vtsi.Calls/DeleteListener',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenerRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenerResponse.FromString,
            _registered_method=True)
        self.DeleteListeners = channel.unary_unary(
            '/ondewo.vtsi.Calls/DeleteListeners',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenersRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenersResponse.FromString,
            _registered_method=True)
        self.StartScheduledCaller = channel.unary_unary(
            '/ondewo.vtsi.Calls/StartScheduledCaller',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallerRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallerResponse.FromString,
            _registered_method=True)
        self.StartScheduledCallers = channel.unary_unary(
            '/ondewo.vtsi.Calls/StartScheduledCallers',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallersRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallersResponse.FromString,
            _registered_method=True)
        self.StopCall = channel.unary_unary(
            '/ondewo.vtsi.Calls/StopCall',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallResponse.FromString,
            _registered_method=True)
        self.StopCalls = channel.unary_unary(
            '/ondewo.vtsi.Calls/StopCalls',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallsRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallsResponse.FromString,
            _registered_method=True)
        self.StopAllCalls = channel.unary_unary(
            '/ondewo.vtsi.Calls/StopAllCalls',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopAllCallsRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallsResponse.FromString,
            _registered_method=True)
        self.TransferCall = channel.unary_unary(
            '/ondewo.vtsi.Calls/TransferCall',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallResponse.FromString,
            _registered_method=True)
        self.TransferCalls = channel.unary_unary(
            '/ondewo.vtsi.Calls/TransferCalls',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallsRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallsResponse.FromString,
            _registered_method=True)
        self.GetCall = channel.unary_unary(
            '/ondewo.vtsi.Calls/GetCall',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.GetCallRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.Call.FromString,
            _registered_method=True)
        self.ListCalls = channel.unary_unary(
            '/ondewo.vtsi.Calls/ListCalls',
            request_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallsRequest.SerializeToString,
            response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallsResponse.FromString,
            _registered_method=True)


class CallsServicer(object):
    """ONDEWO VTSI API
    """

    def StartCaller(self, request, context):
        """////////////////////////////////////////////////////////////////////////////
        Caller and Listener endpoints
        ////////////////////////////////////////////////////////////////////////////

        start single caller instance for a specific nlu-project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCallers(self, request, context):
        """start multiple ondewo-sip callers instances for a specific nlu-project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCallers(self, request, context):
        """lists all available callers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCaller(self, request, context):
        """gets a caller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCaller(self, request, context):
        """deletes a caller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCallers(self, request, context):
        """deletes multiple callers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCaller(self, request, context):
        """stops a caller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCallers(self, request, context):
        """stops multiple callers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartListener(self, request, context):
        """start single listener instance for a specific nlu-project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartListeners(self, request, context):
        """start multiple ondewo-sip listeners instances for a specific nlu-project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopListener(self, request, context):
        """stop a ondewo-sip listeners instances for a specific nlu-project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopListeners(self, request, context):
        """stop multiple ondewo-sip listeners instances for a specific nlu-project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListListeners(self, request, context):
        """lists all available listeners
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetListener(self, request, context):
        """gets a listener
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteListener(self, request, context):
        """deletes a listener
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteListeners(self, request, context):
        """deletes multiple listeners
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartScheduledCaller(self, request, context):
        """start multiple ondewo-sip callers instances with schedules
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartScheduledCallers(self, request, context):
        """start multiple ondewo-sip callers instances with schedules
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCall(self, request, context):
        """stop/kill a ondewo-sip listener or caller instance for a specific vtsi-project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCalls(self, request, context):
        """stop/kill a list of ondewo-sip listener or caller instances for a specific vtsi-project.
        "stops both Listener and Caller calls"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAllCalls(self, request, context):
        """stop/kill all ondewo-sip listener or caller instance for a specific nlu-project.
        "stops all Listener and Caller calls"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferCall(self, request, context):
        """Transfer a call from a listener to another
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferCalls(self, request, context):
        """Transfer a call from a listener to another
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCall(self, request, context):
        """get call log for single call instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCalls(self, request, context):
        """get call log for all call instances
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CallsServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'StartCaller': grpc.unary_unary_rpc_method_handler(
            servicer.StartCaller,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallerRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallerResponse.SerializeToString,
        ),
        'StartCallers': grpc.unary_unary_rpc_method_handler(
            servicer.StartCallers,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallersRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallersResponse.SerializeToString,
        ),
        'ListCallers': grpc.unary_unary_rpc_method_handler(
            servicer.ListCallers,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallersRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallersResponse.SerializeToString,
        ),
        'GetCaller': grpc.unary_unary_rpc_method_handler(
            servicer.GetCaller,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.GetCallerRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.Caller.SerializeToString,
        ),
        'DeleteCaller': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteCaller,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallerRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallerResponse.SerializeToString,
        ),
        'DeleteCallers': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteCallers,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallersRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallersResponse.SerializeToString,
        ),
        'StopCaller': grpc.unary_unary_rpc_method_handler(
            servicer.StopCaller,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallerRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallerResponse.SerializeToString,
        ),
        'StopCallers': grpc.unary_unary_rpc_method_handler(
            servicer.StopCallers,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallersRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallersResponse.SerializeToString,
        ),
        'StartListener': grpc.unary_unary_rpc_method_handler(
            servicer.StartListener,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenerRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenerResponse.SerializeToString,
        ),
        'StartListeners': grpc.unary_unary_rpc_method_handler(
            servicer.StartListeners,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenersRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenersResponse.SerializeToString,
        ),
        'StopListener': grpc.unary_unary_rpc_method_handler(
            servicer.StopListener,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenerRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenerResponse.SerializeToString,
        ),
        'StopListeners': grpc.unary_unary_rpc_method_handler(
            servicer.StopListeners,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenersRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenersResponse.SerializeToString,
        ),
        'ListListeners': grpc.unary_unary_rpc_method_handler(
            servicer.ListListeners,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListListenersRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListListenersResponse.SerializeToString,
        ),
        'GetListener': grpc.unary_unary_rpc_method_handler(
            servicer.GetListener,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.GetListenerRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.Listener.SerializeToString,
        ),
        'DeleteListener': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteListener,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenerRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenerResponse.SerializeToString,
        ),
        'DeleteListeners': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteListeners,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenersRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenersResponse.SerializeToString,
        ),
        'StartScheduledCaller': grpc.unary_unary_rpc_method_handler(
            servicer.StartScheduledCaller,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallerRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallerResponse.SerializeToString,
        ),
        'StartScheduledCallers': grpc.unary_unary_rpc_method_handler(
            servicer.StartScheduledCallers,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallersRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallersResponse.SerializeToString,
        ),
        'StopCall': grpc.unary_unary_rpc_method_handler(
            servicer.StopCall,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallResponse.SerializeToString,
        ),
        'StopCalls': grpc.unary_unary_rpc_method_handler(
            servicer.StopCalls,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallsRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallsResponse.SerializeToString,
        ),
        'StopAllCalls': grpc.unary_unary_rpc_method_handler(
            servicer.StopAllCalls,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopAllCallsRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallsResponse.SerializeToString,
        ),
        'TransferCall': grpc.unary_unary_rpc_method_handler(
            servicer.TransferCall,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallResponse.SerializeToString,
        ),
        'TransferCalls': grpc.unary_unary_rpc_method_handler(
            servicer.TransferCalls,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallsRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallsResponse.SerializeToString,
        ),
        'GetCall': grpc.unary_unary_rpc_method_handler(
            servicer.GetCall,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.GetCallRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.Call.SerializeToString,
        ),
        'ListCalls': grpc.unary_unary_rpc_method_handler(
            servicer.ListCalls,
            request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallsRequest.FromString,
            response_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ondewo.vtsi.Calls', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ondewo.vtsi.Calls', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class Calls(object):
    """ONDEWO VTSI API
    """

    @staticmethod
    def StartCaller(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StartCaller',
            ondewo_dot_vtsi_dot_calls__pb2.StartCallerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StartCallerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartCallers(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StartCallers',
            ondewo_dot_vtsi_dot_calls__pb2.StartCallersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StartCallersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCallers(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/ListCallers',
            ondewo_dot_vtsi_dot_calls__pb2.ListCallersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.ListCallersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCaller(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/GetCaller',
            ondewo_dot_vtsi_dot_calls__pb2.GetCallerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.Caller.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCaller(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/DeleteCaller',
            ondewo_dot_vtsi_dot_calls__pb2.DeleteCallerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.DeleteCallerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCallers(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/DeleteCallers',
            ondewo_dot_vtsi_dot_calls__pb2.DeleteCallersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.DeleteCallersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCaller(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopCaller',
            ondewo_dot_vtsi_dot_calls__pb2.StopCallerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopCallerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCallers(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopCallers',
            ondewo_dot_vtsi_dot_calls__pb2.StopCallersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopCallersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartListener(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StartListener',
            ondewo_dot_vtsi_dot_calls__pb2.StartListenerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StartListenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartListeners(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StartListeners',
            ondewo_dot_vtsi_dot_calls__pb2.StartListenersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StartListenersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopListener(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopListener',
            ondewo_dot_vtsi_dot_calls__pb2.StopListenerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopListenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopListeners(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopListeners',
            ondewo_dot_vtsi_dot_calls__pb2.StopListenersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopListenersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListListeners(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/ListListeners',
            ondewo_dot_vtsi_dot_calls__pb2.ListListenersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.ListListenersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetListener(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/GetListener',
            ondewo_dot_vtsi_dot_calls__pb2.GetListenerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.Listener.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteListener(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/DeleteListener',
            ondewo_dot_vtsi_dot_calls__pb2.DeleteListenerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.DeleteListenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteListeners(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/DeleteListeners',
            ondewo_dot_vtsi_dot_calls__pb2.DeleteListenersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.DeleteListenersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartScheduledCaller(request,
                             target,
                             options=(),
                             channel_credentials=None,
                             call_credentials=None,
                             insecure=False,
                             compression=None,
                             wait_for_ready=None,
                             timeout=None,
                             metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StartScheduledCaller',
            ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartScheduledCallers(request,
                              target,
                              options=(),
                              channel_credentials=None,
                              call_credentials=None,
                              insecure=False,
                              compression=None,
                              wait_for_ready=None,
                              timeout=None,
                              metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StartScheduledCallers',
            ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCall(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopCall',
            ondewo_dot_vtsi_dot_calls__pb2.StopCallRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCalls(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopCalls',
            ondewo_dot_vtsi_dot_calls__pb2.StopCallsRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAllCalls(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopAllCalls',
            ondewo_dot_vtsi_dot_calls__pb2.StopAllCallsRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferCall(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/TransferCall',
            ondewo_dot_vtsi_dot_calls__pb2.TransferCallRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.TransferCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferCalls(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/TransferCalls',
            ondewo_dot_vtsi_dot_calls__pb2.TransferCallsRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.TransferCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCall(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/GetCall',
            ondewo_dot_vtsi_dot_calls__pb2.GetCallRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.Call.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCalls(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/ListCalls',
            ondewo_dot_vtsi_dot_calls__pb2.ListCallsRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.ListCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
