# coding: utf-8

"""
    DataForSEO API documentation

    DataForSEO API is the starting point on your journey towards building powerful SEO software. With DataForSEO you can get all the data you need to build an efficient application while also saving your time and budget. DataForSEO API is using the REST technology for interchanging data between your application and our service. The data exchange is made through the widely used HTTP protocol, which allows applying our API to almost all programming languages.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dataforseo_client.models.app_intersection_info import AppIntersectionInfo

class TestAppIntersectionInfo(unittest.TestCase):
    """AppIntersectionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppIntersectionInfo:
        """Test AppIntersectionInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppIntersectionInfo`
        """
        model = AppIntersectionInfo()
        if include_optional:
            return AppIntersectionInfo(
                google = dataforseo_client.models.app_intersection_google_dataforseo_labs_available_filters_google_info.AppIntersectionGoogleDataforseoLabsAvailableFiltersGoogleInfo(
                    keyword_data/keyword = '', 
                    keyword_data/keyword_info/last_updated_time = '', 
                    keyword_data/keyword_info/search_volume = '', 
                    keyword_data/serp_info/check_url = '', 
                    keyword_data/serp_info/se_results_count = 56, 
                    keyword_data/serp_info/last_updated_time = '', 
                    keyword_data/serp_info/previous_updated_time = '', 
                    intersection_result/__app_id/type = '', 
                    intersection_result/__app_id/rank_group = '', 
                    intersection_result/__app_id/rank_absolute = '', 
                    intersection_result/__app_id/position = '', 
                    intersection_result/__app_id/title = '', 
                    intersection_result/__app_id/url = '', 
                    intersection_result/__app_id/reviews_count = '', 
                    intersection_result/__app_id/is_free = '', 
                    intersection_result/__app_id/developer = '', 
                    intersection_result/__app_id/developer_url = '', ),
                apple = dataforseo_client.models.apple_info.AppleInfo(
                    keyword_data/keyword = '', 
                    keyword_data/keyword_info/last_updated_time = '', 
                    keyword_data/keyword_info/search_volume = '', 
                    keyword_data/serp_info/check_url = '', 
                    keyword_data/serp_info/se_results_count = 56, 
                    keyword_data/serp_info/last_updated_time = '', 
                    keyword_data/serp_info/previous_updated_time = '', 
                    intersection_result/__app_id/type = '', 
                    intersection_result/__app_id/rank_group = '', 
                    intersection_result/__app_id/rank_absolute = '', 
                    intersection_result/__app_id/position = '', 
                    intersection_result/__app_id/title = '', 
                    intersection_result/__app_id/url = '', 
                    intersection_result/__app_id/reviews_count = '', 
                    intersection_result/__app_id/is_free = '', )
            )
        else:
            return AppIntersectionInfo(
        )
        """

    def testAppIntersectionInfo(self):
        """Test AppIntersectionInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
