class NmkRootConfig:
    BASE_DIR = "BASEDIR"
    ROOT_DIR = "ROOTDIR"
    ROOT_NMK_DIR = "ROOTDIR_NMK"
    CACHE_DIR = "CACHEDIR"
    PROJECT_DIR = "PROJECTDIR"
    PROJECT_NMK_DIR = "PROJECTDIR_NMK"
    PROJECT_FILES = "PROJECTFILES"
    ENV = "ENV"
