RESOURCE_CREATE_STATUS_CODE = "CREATE_IN_PROGRESS"
RESOURCE_CREATE_STATUS_CODE_LIST = ["CREATE_IN_PROGRESS", "CREATE_CLEAR_IN_PROGRESS", "CREATE_CLEAR_FAILED", "CREATE_CLUSTER_IN_PROGRESS", "CREATE_NODEGROUP_IN_PROGRESS", "CREATE_NAS_IN_PROGRESS", "CREATE_K8S_RESOURCES_IN_PROGRESS", "CREATE_KUBEFLOW_PIPELINE_RUN_IN_PROGRESS"]
RESOURCE_FAIL_STATUS_CODE = "CREATE_FAILED"
RESOURCE_FAIL_STATUS_CODE_LIST = ["CREATE_FAILED", "FAILED_TO_CREATE_CLUSTER", "FAILED_TO_CREATE_NODEGROUP", "FAILED_TO_CREATE_NAS", "FAILED_TO_CREATE_K8S_RESOURCES", "FAILED_TO_CREATE_KUBEFLOW_PIPELINE_RUN"]

RESOURCE_STOP_IN_PROGRESS_CODE = "STOP_IN_PROGRESS"
RESOURCE_STOP_IN_PROGRESS_CODE_LIST = ["STOP_IN_PROGRESS", "STOP_FAILED"]

RESOURCE_COMPLETE_IN_PROGRESS_CODE = "COMPLETE_IN_PROGRESS"
RESOURCE_COMPLETE_IN_PROGRESS_CODE_LIST = ["COMPLETE_IN_PROGRESS", "COMPLETE_FAILED"]

RESOURCE_FAIL_TRAIN_IN_PROGRESS_CODE = "FAIL_TRAIN_IN_PROGRESS"
RESOURCE_FAIL_TRAIN_IN_PROGRESS_CODE_LIST = ["FAIL_TRAIN_IN_PROGRESS", "FAIL_TRAIN_FAILED"]

RESOURCE_FAIL_PIPELINE_RUN_IN_PROGRESS_CODE = "FAIL_PIPELINE_RUN_IN_PROGRESS"
RESOURCE_FAIL_PIPELINE_RUN_IN_PROGRESS_CODE_LIST = ["FAIL_PIPELINE_RUN_IN_PROGRESS", "FAIL_PIPELINE_RUN_FAILED"]


def replace_status_code(status):
    if status in RESOURCE_CREATE_STATUS_CODE_LIST:
        return RESOURCE_CREATE_STATUS_CODE
    elif status in RESOURCE_FAIL_STATUS_CODE_LIST:
        return RESOURCE_FAIL_STATUS_CODE
    elif status in RESOURCE_STOP_IN_PROGRESS_CODE_LIST:
        return RESOURCE_STOP_IN_PROGRESS_CODE
    elif status in RESOURCE_COMPLETE_IN_PROGRESS_CODE_LIST:
        return RESOURCE_COMPLETE_IN_PROGRESS_CODE
    elif status in RESOURCE_FAIL_TRAIN_IN_PROGRESS_CODE_LIST:
        return RESOURCE_FAIL_TRAIN_IN_PROGRESS_CODE
    elif status in RESOURCE_FAIL_PIPELINE_RUN_IN_PROGRESS_CODE_LIST:
        return RESOURCE_FAIL_PIPELINE_RUN_IN_PROGRESS_CODE
    else:
        return status
