
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-19T16:06:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f523d5bbef72e41370c11a5bfa47f8d6ae2e650",
 "version": "1.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
