# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations

import lapidary.runtime
import pydantic
import typing_extensions as typing
import gsmtasks.components.schemas.TasksStatesCountResponse.properties.dates.schema


class TasksStatesCountResponse(lapidary.runtime.ModelBase):
    dates: typing.Union[None, gsmtasks.components.schemas.TasksStatesCountResponse.properties.dates.schema.dates] = None

    model_config = pydantic.ConfigDict(
        extra='allow'
    )
