# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations

import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import gsmtasks.components.schemas.Metafields.schema
import gsmtasks.components.schemas.NestedAddress.schema
import gsmtasks.components.schemas.NestedContactAddress.schema
import gsmtasks.components.schemas.TaskCommandTaskData.properties.duration.schema


class TaskCommandTaskData(lapidary.runtime.ModelBase):
    scheduled_time: typing.Union[None, datetime.datetime] = None

    position: typing.Annotated[
        typing.Union[None, float],
        pydantic.Field(
            ge=0,
            le=253402300799,
        )
    ] = None

    metafields: typing.Union[None, gsmtasks.components.schemas.Metafields.schema.Metafields] = None

    address: typing.Union[None, gsmtasks.components.schemas.NestedAddress.schema.NestedAddress] = None

    contact_address: typing.Union[None, gsmtasks.components.schemas.NestedContactAddress.schema.NestedContactAddress] = None

    route: typing.Union[None, str] = None

    duration: typing.Union[None, gsmtasks.components.schemas.TaskCommandTaskData.properties.duration.schema.duration] = None

    model_config = pydantic.ConfigDict(
        extra='allow'
    )
