SCOPES_DEFAULT = (
    "project:read",
    "project:list",
    "project:user:list",
    "project:user:read",
    "project:role:list",
    "docs:object:create",
    "docs:signing:list",
    "docs:signing:create",
    "docs:folder:list",
    "docs:folder:create",
    "docs:folder:update",
    "docs:item:create",
    "docs:item:list",
    "docs:item:read",
    "docs:version:create",
    "docs:version:create",
    "docs:version:list"
)
